In [2]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

In [2]:
%matplotlib inline
import os
import time
import pandas as pd
import numpy as np
import sys
import math
import cPickle as pickle
import scipy
import matplotlib.pyplot as plt
from bokeh.plotting import *
from bokeh.models import ColumnDataSource
from scipy.stats import bernoulli

In [4]:
import seaborn as sns
sns.set_style("whitegrid")
sns.set_context("poster")

# Heading1

## Heading 2

### Heading 3

#### Heading 4

## Python List

In [5]:
ls = []
for i in xrange(10):
    ls.append(i)
print ls

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


## Latex

this is inline $\lambda = 1$.

This is a separate equation $$\lambda = 1$$ next line

$$\begin{equation} x = 1 \end{equation}$$


## Numpy Array

In [6]:
# define numpy array
arr1 = np.array([0,1,2])
print arr1
# empty
arr2 = np.empty([1,3])
print arr2
#  zeros
arr3 = np.zeros([1,3])
print arr3
#  ones
arr4 = np.ones([1,3])
print arr4

[0 1 2]
[[ 0.  0.  0.]]
[[ 0.  0.  0.]]
[[ 1.  1.  1.]]


In [7]:
# Matrix
mat1 = np.array([[2,3,4],[5,6,7]])
print mat1
print mat1.shape
print mat1.T
print mat1.shape[0]

[[2 3 4]
 [5 6 7]]
(2, 3)
[[2 5]
 [3 6]
 [4 7]]
2


In [8]:
mat1.dot(arr1)

array([11, 20])

## Stats

numpy & scipy

In [3]:
# draw random standard normal variable N(0,1)
rand1 = np.random.random([10,5])
print rand1
print rand1.ravel()

[[ 0.717275    0.99029707  0.79454184  0.68283483  0.41942157]
 [ 0.43232855  0.43038007  0.85283536  0.53615521  0.93610564]
 [ 0.3553904   0.03788695  0.97064482  0.51642949  0.20686062]
 [ 0.14507163  0.9150132   0.00686816  0.29911015  0.01140511]
 [ 0.91121568  0.01940248  0.19476435  0.66412976  0.43596185]
 [ 0.9156334   0.22735564  0.13132427  0.09089349  0.37771748]
 [ 0.6624498   0.17550936  0.53648035  0.93561587  0.99486387]
 [ 0.14394678  0.0316345   0.23365306  0.78036805  0.62117662]
 [ 0.65226599  0.75373622  0.47237571  0.18065352  0.32039093]
 [ 0.25004216  0.94144136  0.20847007  0.94252512  0.80070652]]
[ 0.717275    0.99029707  0.79454184  0.68283483  0.41942157  0.43232855
  0.43038007  0.85283536  0.53615521  0.93610564  0.3553904   0.03788695
  0.97064482  0.51642949  0.20686062  0.14507163  0.9150132   0.00686816
  0.29911015  0.01140511  0.91121568  0.01940248  0.19476435  0.66412976
  0.43596185  0.9156334   0.22735564  0.13132427  0.09089349  0.37771748
  0.

In [13]:
kk=(np.random.random([50])/np.reshape(rand1.T,50))
print kk
hh=np.repeat(kk,2)
hh=np.reshape(hh,)
print hh

[  9.38599207e-01   2.28907539e+00   2.07662936e+00   2.63047276e+00
   4.21180160e-01   8.87235610e-01   1.47861150e+00   6.69008380e+00
   4.41790457e-01   5.50086906e-01   8.73897550e-01   1.62024135e-01
   1.61546816e+01   1.71518003e-01   4.38811223e+01   3.77552884e+00
   3.79566459e+00   7.14869886e+00   5.11566522e-01   8.32936266e-01
   6.64782616e-01   3.86929002e-02   7.56704152e-01   4.06636734e+01
   2.51184053e+00   3.01858254e+00   3.70007456e-01   4.33704983e-01
   1.77927038e+00   2.21548938e+00   1.10325600e+00   1.53025997e+00
   8.72462890e-01   1.40898759e+00   5.18088268e-01   4.25821769e+00
   4.38179319e-01   7.75230817e-01   2.39896053e+00   6.58089503e-01
   2.17547857e+00   3.00146169e-01   4.45969337e+00   2.66957914e+01
   7.92622582e-01   1.54725013e+00   9.51345451e-02   6.82313029e-01
   2.22067722e+00   6.86683380e-01]
[[  9.38599207e-01   9.38599207e-01]
 [  2.28907539e+00   2.28907539e+00]
 [  2.07662936e+00   2.07662936e+00]
 [  2.63047276e+00   2.63

In [10]:
%%time
rand2 = np.random.random([10000,5000])

CPU times: user 712 ms, sys: 114 ms, total: 825 ms
Wall time: 833 ms


In [11]:
print rand1[0,1]
print rand1[0][1]

0.270858448987
0.270858448987


In [22]:
print rand1[:,0]
print rand1[0,:]
diff=np.diff(rand1[:])
print diff
diff.ravel()

[ 0.70405923  0.51707882  0.69937233  0.67148519  0.79779027  0.90572797
  0.44642045  0.91924646  0.43378337  0.71233147]
[ 0.70405923  0.27085845  0.15281544  0.06956627  0.23176481]
[[-0.43320078 -0.11804301 -0.08324916  0.16219853]
 [ 0.02599515 -0.52959344  0.4915062  -0.21688693]
 [-0.59607093  0.62946116 -0.57663224  0.48387123]
 [-0.04503394 -0.58077477  0.54235333 -0.20959602]
 [-0.39579199 -0.33343914  0.59851836 -0.43378285]
 [-0.59104067  0.46284417 -0.21075097 -0.4697568 ]
 [-0.37638799  0.33512666 -0.07597778  0.26178737]
 [-0.81579298  0.85992586 -0.84882913 -0.01183107]
 [ 0.14496066 -0.41736966 -0.11185904  0.14625724]
 [ 0.06725084 -0.36496495 -0.03941711  0.30910133]]


array([-0.43320078, -0.11804301, -0.08324916,  0.16219853,  0.02599515,
       -0.52959344,  0.4915062 , -0.21688693, -0.59607093,  0.62946116,
       -0.57663224,  0.48387123, -0.04503394, -0.58077477,  0.54235333,
       -0.20959602, -0.39579199, -0.33343914,  0.59851836, -0.43378285,
       -0.59104067,  0.46284417, -0.21075097, -0.4697568 , -0.37638799,
        0.33512666, -0.07597778,  0.26178737, -0.81579298,  0.85992586,
       -0.84882913, -0.01183107,  0.14496066, -0.41736966, -0.11185904,
        0.14625724,  0.06725084, -0.36496495, -0.03941711,  0.30910133])

In [ ]:
print rand1[:5,0]
print rand1[2:5,3:4]

In [ ]:
print rand1.shape
# this is a vector
print rand1[:,0].shape 

mat1d = rand1[:,0].reshape([10,1])
print mat1d.shape

In [26]:
shape = rand1.shape
rand3=np.random.random([1,1])
rand3.reshape(-1,1)

[[ 0.52867471]]


## Python Function

In [ ]:
# define a square function plus 1
def function1(input1):
    res = input1**2 + 1
    return res

In [ ]:
function1(5)

## Plot

In [ ]:
x = np.random.rand(10)
y = np.random.rand(10)
print (x,y)

In [ ]:
plt.plot(x+1,y+1)
plt.hlines(1.5,1,2)
plt.show()
plt.plot(x,y,'r')
plt.vlines(0.5,0,1)
plt.show()

In [ ]:
plt.scatter(x,y)
plt.show()

In [ ]:
# tap for choices
# Shift+tap for function definition
np.random.binomial(10,0.5)

In [ ]:
whos

In [ ]:
def lognormpdf(x, y):
    """
    Calculate Bernoulli probability density of y, when y ~ B(\frac{\exp(x)}{1+\exp(s)})
    """
    return (np.exp(x)/(1+np.exp(x)))**y * (1.0/(1+np.exp(x)))**(1-y)


In [ ]:
def measure(self, particles, y, t):
        """
        Return the log-pdf value of the measurement
        Args:
         - particles  (array-like): Model specific representation
           of all particles, with first dimension = N (number of particles)
         - y (array-like):  measurement
         - t (float): time-stamp
        Returns:
         (array-like) with first dimension = N, logp(y|x^i)
        """
        N = len(particles)
        lpy = numpy.empty(N)
        g = self.calc_g(particles=particles, t=t)
        R = self.calc_R(particles=particles, t=t)

        
        for i in xrange(N):
            lpy[i] = g(particles[i],y[i])

        return lpy

In [36]:
rand5=np.random.random([2,2])
rand6=np.ones([2,2])
print rand5
print rand6
bernoulli.logpmf(rand6,rand5)

[[ 0.11249407  0.82738521]
 [ 0.27428035  0.80102416]]
[[ 1.  1.]
 [ 1.  1.]]


array([[-2.18485479, -0.18948491],
       [-1.29360451, -0.22186417]])

-2.2072749131897207